# frozen_string_literal: true

require "active_support/all"

require "dry-configurable"
require "dry-struct"
require "singleton"
require "typhoeus"

require_relative "steam_api/version"
require_relative "steam_api/request"
require_relative "steam_api/response"
require_relative "steam_api/failure_handler"

require_relative "steam_api/errors/api_error"
require_relative "steam_api/errors/url_error"

require_relative "steam_api/requestors/base"
require_relative "steam_api/requestors/app_details"
require_relative "steam_api/requestors/app_global_achievements"
require_relative "steam_api/requestors/app_news"
require_relative "steam_api/requestors/game_current_players"
require_relative "steam_api/requestors/player_achievements"
require_relative "steam_api/requestors/player_friends"
require_relative "steam_api/requestors/player_game_stats"
require_relative "steam_api/requestors/player_level"
require_relative "steam_api/requestors/player_owned_games"
require_relative "steam_api/requestors/player_recent_games"
require_relative "steam_api/requestors/player_steamid"
require_relative "steam_api/requestors/player_summaries"

require_relative "steam_api/structs/types"
require_relative "steam_api/structs/base"
require_relative "steam_api/structs/app_details/achievement"
require_relative "steam_api/structs/app_details/category"
require_relative "steam_api/structs/app_details/genre"
require_relative "steam_api/structs/app_details/movie"
require_relative "steam_api/structs/app_details/sub"
require_relative "steam_api/structs/app_details/package_group"
require_relative "steam_api/structs/app_details/requirements"
require_relative "steam_api/structs/app_details/screenshot"
require_relative "steam_api/structs/app_details/details"
require_relative "steam_api/structs/app_global_achievements"
require_relative "steam_api/structs/app_new"
require_relative "steam_api/structs/app_news"
require_relative "steam_api/structs/game_current_players"
require_relative "steam_api/structs/player_summary"
require_relative "steam_api/structs/player_achievements"
require_relative "steam_api/structs/player_friends"
require_relative "steam_api/structs/player_game_stats"
require_relative "steam_api/structs/player_level"
require_relative "steam_api/structs/player_owned_games"
require_relative "steam_api/structs/player_recent_games"
require_relative "steam_api/structs/player_steamid"
require_relative "steam_api/structs/player_summaries"

require_relative "steam_api/structs/requests/abstract"
require_relative "steam_api/structs/requests/storefront_abstract"
require_relative "steam_api/structs/requests/get_app_details"
require_relative "steam_api/structs/requests/get_app_global_achievements"
require_relative "steam_api/structs/requests/get_app_news"
require_relative "steam_api/structs/requests/get_game_current_players"
require_relative "steam_api/structs/requests/get_player_achievements"
require_relative "steam_api/structs/requests/get_player_friends"
require_relative "steam_api/structs/requests/get_player_game_stats"
require_relative "steam_api/structs/requests/get_player_level"
require_relative "steam_api/structs/requests/get_player_owned_games"
require_relative "steam_api/structs/requests/get_player_recent_games"
require_relative "steam_api/structs/requests/get_player_steamid"
require_relative "steam_api/structs/requests/get_player_summaries"

require_relative "steam_api/client"

# Main module
module SteamApi; end
